# Generated by Django 4.2.3 on 2023-07-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("httpresponse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmltag",
            name="html_tag",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
